version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: santander-case-app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:15
    container_name: santander-db
    environment:
      POSTGRES_DB: santanderdb
      POSTGRES_USER: santander
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
